directories:
  logs: ./logs
  epg:
    datas: ./epg/datas
    temp: ./epg/temp

logger:
  level: info
  
api:
  host:
  port:
  username:
  password: 

scheduler: 60 # Interval between each processes in minutes
  